apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-mysql-example
  labels:
    app: example-app
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: google-cloud-key
            secret:
              secretName: example-mysql-secrets
          containers:
          - name: backup-mysql-example
            image: ryderdamen/mysql-backup:10
            imagePullPolicy: Always
            volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
            env:
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: "/var/secrets/google/gcp_service_account.json"
              - name: GCS_FULL_BUCKET_UPLOAD_PATH
                value: "gs://your-google-cloud-project-id-database-backups"
              - name: MYSQL_DATABASE
                value: mysql
              - name: MYSQL_HOST
                value: example-mysql.default.svc.cluster.local
              - name: MYSQL_USER
                valueFrom:
                  secretKeyRef:
                    name: example-mysql-secrets
                    key: mysql_super_user_username
              - name: MYSQL_ROOT_PASSWORD
                valueFrom:
                    secretKeyRef:
                      name: example-mysql-secrets
                      key: mysql_root_password
              - name: MYSQL_PORT
                value: "3306"
          restartPolicy: OnFailure
