apiVersion: batch/v1
kind: Job
metadata:
  name: restore-mysql-example
  labels:
    app: example-app
spec:
  template:
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: example-mysql-secrets
      containers:
      - name: backup-mysql-example
        image: gcr.io/your-google-cloud-project-id/mysql-restore:0.0.1
        imagePullPolicy: Always
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/var/secrets/google/gcp_service_account.json"
          - name: GCS_MYSQL_SNAPSHOT
            value: "gs://your-google-cloud-project-id-database-backups/mysql_backup.tar.gz"
          - name: MYSQL_DATABASE
            value: mysql
          - name: MYSQL_HOST
            value: example-mysql.default.svc.cluster.local
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: example-mysql-secrets
                key: mysql_super_user_username
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: example-mysql-secrets
                key: mysql_root_password
          - name: MYSQL_PORT
            value: "3306"
      restartPolicy: Never
